name: Deploy

on:
  push:
    branches: [main]
    tags: ['v*']

env:
  NODE_VERSION: '20.11.0'

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Deploy to staging
        run: |
          echo "🚧 Staging deployment would happen here"
          echo "Environment: staging"
          echo "Commit: ${{ github.sha }}"

  deploy-production:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Deploy to production
        run: |
          echo "🚀 Production deployment would happen here"
          echo "Environment: production"
          echo "Tag: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            🚀 New release of BMAD platform
            
            **Changes in this release:**
            - See commit history for detailed changes
            
            **Deployment:**
            - Production deployment completed
            - All services updated
          draft: false
          prerelease: false